//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_DVMC.Chuc_Nang {
    
    
    public partial class f0000_gd_dat_hang_gd_log_dat_hang {
        
        /// <summary>
        /// m_grv_gd_dat_hang_gd_log_dat_hang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView m_grv_gd_dat_hang_gd_log_dat_hang;
        
        /// <summary>
        /// m_cmd_BO_tiep_nhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_BO_tiep_nhan;
        
        /// <summary>
        /// m_cmd_BO_tu_choi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_BO_tu_choi;
        
        /// <summary>
        /// m_cmd_cap_nhat_BO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_cap_nhat_BO;
        
        /// <summary>
        /// m_cmd_BO_hoan_thanh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_BO_hoan_thanh;
        
        /// <summary>
        /// m_cmd_bo_chuyen_pm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_bo_chuyen_pm;
        
        /// <summary>
        /// m_cmd_BO_cap_nhat_xu_ly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_BO_cap_nhat_xu_ly;
        
        /// <summary>
        /// m_cmd_PM_tiep_nhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_PM_tiep_nhan;
        
        /// <summary>
        /// m_cmd_PM_dieu_phoi_cho_BO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_PM_dieu_phoi_cho_BO;
        
        /// <summary>
        /// m_cmd_PM_gui_cho_TD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_PM_gui_cho_TD;
        
        /// <summary>
        /// m_cmd_PM_hoan_thanh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_PM_hoan_thanh;
        
        /// <summary>
        /// m_cmd_PM_cap_nhat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_PM_cap_nhat;
        
        /// <summary>
        /// m_cmd_TD_tiep_nhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_TD_tiep_nhan;
        
        /// <summary>
        /// m_cmd_TD_huy_don_hang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_TD_huy_don_hang;
        
        /// <summary>
        /// m_cmd_TD_cap_nhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_TD_cap_nhan;
        
        /// <summary>
        /// m_cmd_TD_hoan_thanh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button m_cmd_TD_hoan_thanh;
    }
}
